repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-merge-conflict
  - id: check-yaml
  - id: double-quote-string-fixer
  - id: end-of-file-fixer
  - id: mixed-line-ending
    args: [--fix=lf]
  - id: trailing-whitespace

- repo: https://github.com/ikamensh/flynt/
  rev: 1.0.6
  hooks:
  - id: flynt

- repo: https://github.com/asottile/pyupgrade
  rev: v3.21.2
  hooks:
  - id: pyupgrade

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.16.0
  hooks:
  - id: pretty-format-toml
    args: [--autofix]
  - id: pretty-format-yaml
    args: [--autofix]
